### PR TITLE
Implement read_pdf_with_template() function

### LINKED ISSUE #111: It would be nice to be able to include a template (json file tabula-template) directly as an option of tabula-py
(This is a reopening of #110, opened by made to fit the issue template. This was originally submitted by @papagala but I have the same need, AFAICT)

**Is your feature request related to a problem? Please describe.**
I have PDFs with many pages, each presenting a table with the same (lined) structure, but filled differently (some boxes are empty, some are filled, the length varies, it depends on the page). The empty cell and varying lengths of entries mess up the table structure detection, enough that each table is understood to have a slightly different structure, and as a result the JSON output has a different structure page-per-page. 

Note that, in my case, I am actually trying to devise a solution that will assist each of my users in analysing their PDF file consisting of many pages, many tables, etc. The actual content is personal data. To fix ideas, think of me pre-programming a little python script to assist in scraping a PDF printout of their bank statement. 

This is my own problem, but maybe @papagala's is different. 

**Describe the solution you'd like**
My problem can already be partially managed in the following way: from the structure extracted from each page (through method described in #102, for instance), I can figure out programmatically, with some basic logic, which unique structure to use across all the pages. The problem is that I don't have a way to then tell `tabula-py` to use this structure to reanalyse the whole document. 

I imagine I could pass on that structure as a tabula template to `read_pdf`, but AFAICT this functionality is not available right now (but is available in tabula java?). 

**Describe alternatives you've considered**
I could:
 1. use tabula on each page; 
 2. output some JSON;
 3. look at the position of the cells (see #102);
 4. try to reconcile these cell positions across the pages into a global template;
 5. go back, page by page, to transform the JSON output to fit the global template.

I assess 4. to be of medium difficulty and 5. to be hard. Much better would be to, instead of 5., re-use tabula based on the global template.

In my particular situation, where I have to prepare this for others to use, this alternative would be messy, error-prone, and very unlikely to be fixed by end-users.

### PR DESCRIPTION
**Pull request by chezou**
This PR introduces extract PDF with Tabula app JSON templates.

Close #111 

Example:

```py
In [7]: dfs = tabula.read_pdf_with_template('./examples/data.pdf', './examples/data.tabula-template.json', pandas_options={'header': 0})

In [8]: dfs[0]
Out[8]:
             Unnamed: 0   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  \
0             Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1
1         Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1
2            Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1
3        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0
4     Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0
5               Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0
6            Duster 360  14.3    8  360.0  245  3.21  3.570  15.84   0   0
7             Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0
8              Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0
9              Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0
10            Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0
11           Merc 450SE  16.4    8  275.8  180  3.07  4.070  17.40   0   0
12           Merc 450SL  17.3    8  275.8  180  3.07  3.730  17.60   0   0
13          Merc 450SLC  15.2    8  275.8  180  3.07  3.780  18.00   0   0
14   Cadillac Fleetwood  10.4    8  472.0  205  2.93  5.250  17.98   0   0
15  Lincoln Continental  10.4    8  460.0  215  3.00  5.424  17.82   0   0
16    Chrysler Imperial  14.7    8  440.0  230  3.23  5.345  17.42   0   0
17             Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1
18          Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1
19       Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1
20        Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0
21     Dodge Challenger  15.5    8  318.0  150  2.76  3.520  16.87   0   0
22          AMC Javelin  15.2    8  304.0  150  3.15  3.435  17.30   0   0
23           Camaro Z28  13.3    8  350.0  245  3.73  3.840  15.41   0   0
24     Pontiac Firebird  19.2    8  400.0  175  3.08  3.845  17.05   0   0
25            Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1
26        Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1
27         Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1
28       Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.50   0   1
29         Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1
30        Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.60   0   1
31           Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1

    gear  carb
0      4     4
1      4     4
2      4     1
3      3     1
4      3     2
5      3     1
6      3     4
7      4     2
8      4     2
9      4     4
10     4     4
11     3     3
12     3     3
13     3     3
14     3     4
15     3     4
16     3     4
17     4     1
18     4     2
19     4     1
20     3     1
21     3     2
22     3     2
23     3     4
24     3     2
25     4     1
26     5     2
27     5     2
28     5     4
29     5     6
30     5     8
31     4     2

In [9]: dfs[1]
Out[9]:
       Sepal.Width Petal.Length Petal.Width Species
0  5.1         3.5          1.4         0.2  setosa
1  4.9         3.0          1.4         0.2  setosa
2  4.7         3.2          1.3         0.2  setosa
3  4.6         3.1          1.5         0.2  setosa
4  5.0         3.6          1.4         0.2  setosa

In [10]: dfs[2]
Out[10]:
       Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
0  145          6.7         3.3          5.7         2.5  virginica
1  146          6.7         3.0          5.2         2.3  virginica
2  147          6.3         2.5          5.0         1.9  virginica
3  148          6.5         3.0          5.2         2.0  virginica
4  149          6.2         3.4          5.4         2.3  virginica

In [11]: dfs[3]
Out[11]:
     len supp  dose
0    4.2   VC   0.5
1   11.5   VC   0.5
2    7.3   VC   0.5
3    5.8   VC   0.5
4    6.4   VC   0.5
5   10.0   VC   0.5
6   11.2   VC   0.5
7   11.2   VC   0.5
8    5.2   VC   0.5
9    7.0   VC   0.5
10  16.5   VC   1.0
11  16.5   VC   1.0
12  15.2   VC   1.0
13  17.3   VC   1.0
14  22.5   VC   1.0
```

### CODE REVIEW

**Comment by chezou** [comment]
After CI passing, I will merge.

**Comment by papagala** [comment]
Wow man you are incredible. Thanks for the passion you showed! I will test it, thanks a lot!

**Comment by KunalGehlot** [comment]
Is there any documentation regarding this function? I can't seem to find one. 

I want to know what parameters I can pass in and what does `width` and `height` mean?

**Comment by chezou** [comment]
@KunalGehlot As [document says](https://github.com/tabulapdf/tabula/pull/711), this function enables to load template which is created by Tabula app, not tabula-py.
See detail in: https://github.com/tabulapdf/tabula/pull/711

**Pull request merged**
