### PR TITLE
Convert_into add wrap text option on a column

### PR DESCRIPTION
**Pull request by nacu4**
Very new to Github, python, and tabula so I apologize if I submitted this incorrectly. 

I have a PDF where the text in a given column is sometimes "wrapped" meaning that table populates a second row for that data even though it's one record to the human eye. Would it be possible to add a "wrap" yes/no option on the convert_into option? 

Let me know what additional detail you need.

### CODE REVIEW

**Comment by chezou** [comment]
@nacu4 Not sure why you send a PR to `multiple_tables` branch, but can you recreate a PR to master? Also, I couldn't understand your motivation to change, I'd like to see a detailed background with example code.

**Comment by nacu4** [comment]
@chezou Github forced me to choose branches to compare? But now I can't even create a PR because my only options are master and master. And the button is disabled with those as my options. I click New Pull Request and it takes me to "Code" section... so I'm not sure what I'm doing wrong. Below is the snapshot of my PDF and my code. The issue with this code is that, on Line Item 012, the text "Single Row" gets put onto it's own row in the CSV. If possible, I'd like to be able to configure my code so that my CSV always has 1 or 2 rows per "Line Item": The Description and the Item Number, like it has in Line Item 013. 

In my code, within columns or area or something, be able to say "Wrap Text: Yes" with an additional input of either "Header" "Line Item%" or "Lowest Row" "Item No:%". Or something along those lines. 

Does that make sense? 

tabula.convert_into("Test.pdf", "Test.csv", output_format="csv",pages='all',
area = (1,37.18,1000,574.68),
columns = (34.51,190.73,298.73,374.33,422.93,498.53,571.13)
)

Capture

**Comment by chezou** [comment]
@nacu4 Could you have a read the document before sending a PR? https://help.github.com/en/desktop/contributing-to-projects/working-with-your-remote-repository-on-github-or-github-enterprise
Thanks!

**Comment by nacu4** [comment]
@chezou I'm sorry I don't understand. Where should I create a remote repository? I can submit somewhere else. I'm just trying to learn to navigate the site

**Comment by chezou** [comment]
my bad. here is the right document you have to read.
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests

Unfortunately, I'm not a GitHub support guy, I can't continue to teach how to use GitHub. Read the doc and try to learn.

Thanks!

**Comment by nacu4** [comment]
@chezou  understood. And thanks for that link. Can you add me as a collaborator for this repo? Looks like I just need to create a custom branch but I can't until I'm a collaborator. Once I am, I'll create a branch and then create a new pull request.

**Comment by chezou** [comment]
No, you need fork the branch. I'm sorry but I don't want to continue supporting about GitHub. I will lock this PR. Read the doc through again.

**Pull request closed without merging**
