### PR TITLE
Update to new Tabula Version

### PR DESCRIPTION
**Pull request by nl5001**

### CODE REVIEW

**Comment by chezou** [comment]
Thanks for your PR, but CI was failed https://travis-ci.org/chezou/tabula-py/builds/200762736 .
How was the result of `py.test --doctest-module -v tabula/wrapper.py tests`?

**Comment by chezou** [comment]
@nl5001  Thanks for your PR, but CI was failed https://travis-ci.org/chezou/tabula-py/builds/200762736 .
How was the result of `py.test --doctest-module -v tabula/wrapper.py tests`?

**Comment by nl5001** [comment]
Oh sorry, I just called the functions, I rework it again.

**Comment by chezou** [comment]
It seems differences of old version and new one is the route cause. I usually create test files with tabula-java using same options. You don't need to close this PR. If you want to continue, please reopen it and clarify what difference of output is.

**Comment by chezou** [comment]
@nl5001 Hey, CI still fails. Could you check the results?

**Comment by chezou** [comment]
I bumped up with #20 . After merging, I will bump up on PyPI.

**Pull request closed without merging**
